[package]
name = "keidc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
keid = { path = "../keid" }

[[bin]]
name = "keidc"
path = "src/main.rs"
